services:
  neo4j:
    image: neo4j:4.2.19-community
    container_name: skrid-neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=${NEO4J_USER}/${NEO4J_PASSWORD}
    volumes:
      - ./neo4j/neo4j_data:/data
      - ./neo4j/neo4j_config/neo4j.conf:/conf/neo4j.conf
      - ./neo4j/neo4j_config/plugins:/plugins
      - ./neo4j/neo4j_import:/import
    restart: unless-stopped

  backend:
    build:
      context: ./backend
    container_name: skrid-backend
    depends_on:
      - neo4j
    ports:
      - "5000:5000"
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=${NEO4J_USER}
      - NEO4J_PASSWORD=${NEO4J_PASSWORD}
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    container_name: skrid-frontend
    ports:
      - "3000:3000"
    environment:
      - API_BASE_URL=http://backend:5000
      - BASE_PATH=
    volumes:
      - ./frontend/assets/data:/app/assets/data
    depends_on:
      - backend
    restart: unless-stopped
