services:
  neo4j:
    image: neo4j:4.2.19-community
    container_name: skrid-neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=${NEO4J_USER}/${NEO4J_PASSWORD}
    volumes:
      - ./neo4j/neo4j_data:/data
      - ./neo4j/neo4j_config/neo4j.conf:/conf/neo4j.conf
      - ./neo4j/neo4j_config/plugins:/plugins
      - ./neo4j/neo4j_import:/import
    restart: unless-stopped

